# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 周中原的网络日志
email: yaewnzhongyuan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  关注前端技术:Javascript, Web app, Cordova, React, Backbone
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhouzhongyuan.com" # the base hostname & protocol for your site
twitter_username: zhouzhongyuan
github_username:  zhouzhongyuan

# Build settings
markdown: kramdown
